using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace KubernetesClient.StrategicPatch.SourceGenerators;

/// <summary>
/// Renders the generator's <see cref="WireFormat.WireDoc"/> into the C# source emitted into
/// the consuming compilation. Three responsibilities:
/// <list type="bullet">
///   <item>Emit a <c>partial class GeneratedStrategicPatchSchemaProvider : IManifestedSchemaProvider</c>
///         in the consumer's compilation that exposes a frozen GVK→<c>SchemaNode</c> dictionary
///         and an <see cref="GenerationManifest"/>.</item>
///   <item>For each GVK, emit a per-GVK <c>private static SchemaNode Build_{group}_{version}_{kind}()</c>
///         method that constructs the schema tree by calling <c>SchemaBuilder.*</c>. The dispatcher
///         dictionary just calls the per-GVK methods, keeping each readable in isolation.</item>
///   <item>Compute a stable <see cref="GenerationManifest.SnapshotContentHash"/> (SHA-256 of the
///         schemas.json bytes) so consumers can correlate runtime traces to a specific snapshot.</item>
/// </list>
/// </summary>
internal static class SourceWriter
{
    private const string ProviderClassName = "GeneratedStrategicPatchSchemaProvider";
    private const string ProviderNamespace = "KubernetesClient.StrategicPatch.Generated";

    public static string Emit(byte[] schemaBytes, WireFormat.WireDoc doc, string libraryVersion)
    {
        var hash = ComputeSha256Hex(schemaBytes);
        var generatedAt = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture);
        var schemas = doc.Schemas ?? new Dictionary<string, WireFormat.WireNode>();

        var sb = new StringBuilder(64 * 1024);
        WriteHeader(sb);
        sb.AppendLine();
        sb.Append("namespace ").Append(ProviderNamespace).AppendLine(";").AppendLine();

        WriteProviderClass(sb, schemas, generatedAt, doc.Version, libraryVersion, hash);
        return sb.ToString();
    }

    public static string EmitEmpty(string libraryVersion)
    {
        var hash = ComputeSha256Hex(Array.Empty<byte>());
        var generatedAt = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture);

        var sb = new StringBuilder(2048);
        WriteHeader(sb);
        sb.AppendLine();
        sb.Append("namespace ").Append(ProviderNamespace).AppendLine(";").AppendLine();
        WriteProviderClass(sb,
            new Dictionary<string, WireFormat.WireNode>(),
            generatedAt, WireFormat.CurrentVersion, libraryVersion, hash);
        return sb.ToString();
    }

    // ---- writers ----------------------------------------------------------------------------

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Emitted by KubernetesClient.StrategicPatch.SourceGenerators.");
        sb.AppendLine("//   Do not edit by hand — regenerate by re-baking schemas.json (scripts/regen-schemas.sh)");
        sb.AppendLine("//   and rebuilding the consuming project.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using KubernetesClient.StrategicPatch;");
        sb.AppendLine("using KubernetesClient.StrategicPatch.Schema;");
    }

    private static void WriteProviderClass(
        StringBuilder sb,
        IReadOnlyDictionary<string, WireFormat.WireNode> schemas,
        string generatedAtIso,
        int wireVersion,
        string libraryVersion,
        string snapshotHash)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Strategic-merge schema provider emitted by the source generator. Reproduces the GVK set");
        sb.AppendLine("/// of the embedded snapshot but with all schemas materialised at compile time as static");
        sb.AppendLine("/// data — no runtime JSON parse, AOT-friendly, single allocation for the dispatch dictionary.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {ProviderClassName} : IManifestedSchemaProvider");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Process-wide singleton instance. Allocation-free for repeat use.</summary>");
        sb.AppendLine($"    public static {ProviderClassName} Instance {{ get; }} = new();");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public string Name => \"Generated\";");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public GenerationManifest Manifest { get; } = new GenerationManifest(");
        sb.Append("        GeneratedAtUtc: DateTimeOffset.Parse(\"").Append(generatedAtIso).AppendLine("\"),");
        sb.Append("        SchemaWireFormatVersion: ").Append(wireVersion).AppendLine(",");
        sb.Append("        GvkCount: ").Append(schemas.Count).AppendLine(",");
        sb.Append("        LibraryVersion: \"").Append(libraryVersion).AppendLine("\",");
        sb.Append("        SnapshotContentHash: \"").Append(snapshotHash).AppendLine("\");");
        sb.AppendLine();
        sb.AppendLine("    private static readonly FrozenDictionary<GroupVersionKind, SchemaNode> Roots = BuildRoots();");
        sb.AppendLine();
        sb.AppendLine($"    static {ProviderClassName}() => Instance.Manifest.EmitOnce();");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public SchemaNode? GetRootSchema(GroupVersionKind gvk) =>");
        sb.AppendLine("        Roots.TryGetValue(gvk, out var root) ? root : null;");
        sb.AppendLine();
        WriteBuildRootsMethod(sb, schemas);
        sb.AppendLine();
        WritePerGvkMethods(sb, schemas);
        sb.AppendLine("}");
    }

    private static void WriteBuildRootsMethod(StringBuilder sb, IReadOnlyDictionary<string, WireFormat.WireNode> schemas)
    {
        sb.AppendLine("    private static FrozenDictionary<GroupVersionKind, SchemaNode> BuildRoots()");
        sb.AppendLine("    {");
        sb.Append("        var dict = new Dictionary<GroupVersionKind, SchemaNode>(").Append(schemas.Count).AppendLine(");");
        foreach (var entry in schemas.OrderBy(kvp => kvp.Key, StringComparer.Ordinal))
        {
            var (group, version, kind) = ParseGvkKey(entry.Key);
            sb.Append("        dict[new GroupVersionKind(\"")
              .Append(EscapeStringLiteral(group)).Append("\", \"")
              .Append(EscapeStringLiteral(version)).Append("\", \"")
              .Append(EscapeStringLiteral(kind)).Append("\")] = ")
              .Append(BuildMethodName(group, version, kind)).AppendLine("();");
        }
        sb.AppendLine("        return dict.ToFrozenDictionary();");
        sb.AppendLine("    }");
    }

    private static void WritePerGvkMethods(StringBuilder sb, IReadOnlyDictionary<string, WireFormat.WireNode> schemas)
    {
        foreach (var entry in schemas.OrderBy(kvp => kvp.Key, StringComparer.Ordinal))
        {
            var (group, version, kind) = ParseGvkKey(entry.Key);
            sb.Append("    private static SchemaNode ")
              .Append(BuildMethodName(group, version, kind))
              .AppendLine("() =>");
            sb.Append("        ");
            WriteNodeExpression(sb, entry.Value, jsonName: string.Empty, indent: 8);
            sb.AppendLine(";");
            sb.AppendLine();
        }
    }

    private static void WriteNodeExpression(StringBuilder sb, WireFormat.WireNode node, string jsonName, int indent)
    {
        // Decide which SchemaBuilder factory to use based on Kind code.
        switch (node.K)
        {
            case "P":
                WritePrimitive(sb, node, jsonName);
                break;
            case "M":
                WriteMap(sb, node, jsonName, indent);
                break;
            case "L":
                WriteList(sb, node, jsonName, indent);
                break;
            case "O":
                WriteObject(sb, node, jsonName, indent);
                break;
            default:
                throw new InvalidOperationException($"Unknown wire kind '{node.K}'.");
        }
    }

    private static void WritePrimitive(StringBuilder sb, WireFormat.WireNode node, string jsonName)
    {
        // Primitives carry no merge metadata in practice, but if they do we must surface it.
        var hasExtras = node.Mk is not null || node.Ps is not null || node.Lt is not null;
        if (!hasExtras)
        {
            sb.Append("SchemaBuilder.Primitive(\"").Append(EscapeStringLiteral(jsonName)).Append("\")");
            return;
        }
        sb.Append("(SchemaBuilder.Primitive(\"").Append(EscapeStringLiteral(jsonName)).Append("\")");
        AppendWithClause(sb, node);
        sb.Append(")");
    }

    private static void WriteMap(StringBuilder sb, WireFormat.WireNode node, string jsonName, int indent)
    {
        sb.Append("SchemaBuilder.Map(");
        if (node.I is null)
        {
            sb.Append("SchemaBuilder.Primitive()");
        }
        else
        {
            WriteNodeExpression(sb, node.I, jsonName: string.Empty, indent + 4);
        }
        sb.Append(", \"").Append(EscapeStringLiteral(jsonName)).Append("\")");
        if (node.Mk is not null || node.Ps is not null || node.Lt is not null)
        {
            AppendWithClause(sb, node);
        }
    }

    private static void WriteList(StringBuilder sb, WireFormat.WireNode node, string jsonName, int indent)
    {
        sb.Append("SchemaBuilder.ListNode(\"").Append(EscapeStringLiteral(jsonName)).Append("\", ");
        if (node.I is null)
        {
            sb.Append("SchemaBuilder.Primitive()");
        }
        else
        {
            WriteNodeExpression(sb, node.I, jsonName: string.Empty, indent + 4);
        }

        // Optional named arguments — only emit when they differ from defaults.
        var strategy = DecodeStrategy(node.Ps);
        if (strategy is not null)
        {
            sb.Append(", strategy: ").Append(strategy);
        }
        if (node.Mk is not null)
        {
            sb.Append(", patchMergeKey: \"").Append(EscapeStringLiteral(node.Mk)).Append("\"");
        }
        var listType = DecodeListType(node.Lt);
        if (listType is not null)
        {
            sb.Append(", listType: ").Append(listType);
        }
        sb.Append(")");
    }

    private static void WriteObject(StringBuilder sb, WireFormat.WireNode node, string jsonName, int indent)
    {
        var props = node.P;
        var strategy = DecodeStrategy(node.Ps);
        var hasOtherExtras = node.Mk is not null || node.Lt is not null;
        var inner = new string(' ', indent + 4);
        var outer = new string(' ', indent);

        sb.Append("SchemaBuilder.ObjectNode(\"").Append(EscapeStringLiteral(jsonName)).Append("\",");
        sb.AppendLine();
        sb.Append(inner).Append("new Dictionary<string, SchemaNode>");
        if (props is null || props.Count == 0)
        {
            sb.Append("()");
        }
        else
        {
            sb.AppendLine();
            sb.Append(inner).AppendLine("{");
            foreach (var kvp in props.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                sb.Append(inner).Append("    [\"").Append(EscapeStringLiteral(kvp.Key)).Append("\"] = ");
                WriteNodeExpression(sb, kvp.Value, kvp.Key, indent + 8);
                sb.AppendLine(",");
            }
            sb.Append(inner).Append('}');
        }
        if (strategy is not null)
        {
            sb.Append(", strategy: ").Append(strategy);
        }
        sb.AppendLine(")");
        if (hasOtherExtras)
        {
            sb.Append(outer);
            AppendWithClause(sb, node, includeStrategy: false);
        }
        // Trim whatever line-terminator the StringBuilder accumulated so the caller's
        // statement terminator (`;`) lands on the same line. RS1035 bans Environment.NewLine
        // inside analyzers, so probe the buffer directly.
        while (sb.Length > 0 && (sb[sb.Length - 1] == '\n' || sb[sb.Length - 1] == '\r'))
        {
            sb.Length--;
        }
    }

    private static void AppendWithClause(StringBuilder sb, WireFormat.WireNode node, bool includeStrategy = true)
    {
        var fragments = new List<string>();
        if (includeStrategy)
        {
            var strategy = DecodeStrategy(node.Ps);
            if (strategy is not null)
            {
                fragments.Add($"Strategy = {strategy}");
            }
        }
        if (node.Mk is not null)
        {
            fragments.Add($"PatchMergeKey = \"{EscapeStringLiteral(node.Mk)}\"");
        }
        var listType = DecodeListType(node.Lt);
        if (listType is not null)
        {
            fragments.Add($"ListType = {listType}");
        }
        if (fragments.Count == 0)
        {
            return;
        }
        sb.Append(" with { ").Append(string.Join(", ", fragments)).Append(" }");
    }

    // ---- decoders --------------------------------------------------------------------------

    private static string? DecodeStrategy(int? ps)
    {
        if (ps is null || ps == 0)
        {
            return null;
        }
        var flags = new List<string>();
        var v = ps.Value;
        if ((v & 1) != 0) flags.Add("PatchStrategy.Replace");
        if ((v & 2) != 0) flags.Add("PatchStrategy.Merge");
        if ((v & 4) != 0) flags.Add("PatchStrategy.RetainKeys");
        return flags.Count switch
        {
            0 => null,
            1 => flags[0],
            _ => string.Join(" | ", flags),
        };
    }

    private static string? DecodeListType(string? lt) => lt switch
    {
        "a" => "ListType.Atomic",
        "s" => "ListType.Set",
        "m" => "ListType.Map",
        _ => null,
    };

    // ---- helpers ---------------------------------------------------------------------------

    private static (string Group, string Version, string Kind) ParseGvkKey(string key)
    {
        var parts = key.Split('/');
        return parts.Length switch
        {
            2 => (string.Empty, parts[0], parts[1]),
            3 => (parts[0], parts[1], parts[2]),
            _ => throw new InvalidOperationException($"Invalid GVK key '{key}'."),
        };
    }

    private static string BuildMethodName(string group, string version, string kind) =>
        $"Build_{Sanitize(group)}_{Sanitize(version)}_{Sanitize(kind)}";

    private static string Sanitize(string s)
    {
        if (string.IsNullOrEmpty(s))
        {
            return "core";
        }
        var buf = new StringBuilder(s.Length);
        foreach (var c in s)
        {
            buf.Append(IsIdentifierChar(c) ? c : '_');
        }
        // C# identifiers can't start with a digit (e.g. version "v1alpha1" is fine; "1alpha" is not).
        if (char.IsDigit(buf[0]))
        {
            buf.Insert(0, '_');
        }
        return buf.ToString();
    }

    private static bool IsIdentifierChar(char c) =>
        char.IsLetterOrDigit(c) || c == '_';

    private static string EscapeStringLiteral(string s)
    {
        var buf = new StringBuilder(s.Length);
        foreach (var c in s)
        {
            switch (c)
            {
                case '\\': buf.Append("\\\\"); break;
                case '"': buf.Append("\\\""); break;
                case '\r': buf.Append("\\r"); break;
                case '\n': buf.Append("\\n"); break;
                case '\t': buf.Append("\\t"); break;
                default: buf.Append(c); break;
            }
        }
        return buf.ToString();
    }

    private static string ComputeSha256Hex(byte[] bytes)
    {
        using var sha = SHA256.Create();
        var hash = sha.ComputeHash(bytes);
        var sb = new StringBuilder(hash.Length * 2);
        for (var i = 0; i < hash.Length; i++)
        {
            sb.Append(hash[i].ToString("x2", CultureInfo.InvariantCulture));
        }
        return sb.ToString();
    }
}
