blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/JanusMael/KubernetesClient.StrategicPatch/discussions
    about: Use Discussions for questions, ideas, and general conversation.
