using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace KubernetesClient.StrategicPatch.SourceGenerators.Tests;

/// <summary>
/// Placeholder for the source-generator snapshot test harness. Drives the generator pipeline
/// directly via <see cref="CSharpGeneratorDriver"/> rather than depending on the canonical
/// <c>Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.MSTest</c> harness — that
/// package's current stable (1.1.2) carries Roslyn 3.8 and conflicts with
/// <c>IIncrementalGenerator</c>. Direct-driver pattern is what current generator authors use.
/// When the real generator (Stage 13) lands, replace <see cref="NoOpGenerator"/> with the
/// real type and add expected-source assertions.
/// </summary>
[TestClass]
public sealed class HarnessSmokeTests
{
    [TestMethod]
    public void Harness_RunsNoOpGenerator_NoDiagnostics()
    {
        // The "no-op" generator: registers nothing, emits nothing. Compiling a trivial source
        // through it must succeed with zero diagnostics. Establishes that the generator pipeline
        // (driver, syntax tree compilation, generator host) is reachable from a normal MSTest
        // process — the real Stage 13 tests will reuse this scaffolding.
        var inputCompilation = CSharpCompilation.Create(
            "ConsumerAssembly",
            new[] { CSharpSyntaxTree.ParseText("namespace Sandbox { public sealed class C { } }") },
            new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) },
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new NoOpGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation, out var outputCompilation, out var generatorDiagnostics);

        Assert.IsEmpty(generatorDiagnostics);
        Assert.IsEmpty(outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error));
    }

    [TestMethod]
    public void Harness_GenerateAndCaptureSyntaxTrees()
    {
        // Demonstrates how Stage 13's snapshot tests will fish out the generator's emitted
        // sources: drive the generator, then enumerate driver.GetRunResult().Results to read
        // the produced syntax trees.
        var inputCompilation = CSharpCompilation.Create(
            "ConsumerAssembly",
            new[] { CSharpSyntaxTree.ParseText("namespace S { class X {} }") },
            new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) },
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var driver = CSharpGeneratorDriver.Create(new EmitsAFileGenerator());
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            inputCompilation, out _, out _);

        var run = driver.GetRunResult();
        var emitted = run.Results
            .SelectMany(r => r.GeneratedSources)
            .Select(g => (g.HintName, Source: g.SourceText.ToString()))
            .ToImmutableArray();

        Assert.HasCount(1, emitted);
        Assert.AreEqual("smoke.g.cs", emitted[0].HintName);
        StringAssert.Contains(emitted[0].Source, "// generated by EmitsAFileGenerator");
    }

    /// <summary>No-op stub; replace usages with the real generator when Stage 13 lands.</summary>
    private sealed class NoOpGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context) { }
    }

    /// <summary>Tiny stub that emits one fixed file so the snapshot-fishing pattern is testable today.</summary>
    private sealed class EmitsAFileGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(c =>
                c.AddSource("smoke.g.cs", "// generated by EmitsAFileGenerator\n"));
        }
    }
}
